[general]
import = [
  "./catppuccin-macchiato.toml"
]

[env]
TERM = "xterm-256color"

# Window Customization
[window]
padding = { x = 10, y = 10 }
opacity = 0.8
blur = true 
[colors] 
# Включить прозрачные цвета для фона и текста
transparent_background_colors = true

[font]
size = 14.0
#
[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"
#
[font.bold_italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold Italic"
#
[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Italic"
#
[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"
